
services:

  react:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    # No ports exposed
    depends_on:
      - mongodb
    networks:
      - internal

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - react
    networks:
      - internal
      - external

networks:
  internal:
    internal: true
  external:
    external: false
