
services:

  react:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_MULTI_LANGUAGE: ${VITE_MULTI_LANGUAGE}
      VITE_DEFAULT_LANGUAGE: ${VITE_DEFAULT_LANGUAGE}
      VITE_ALLOWED_DOMAINS: ${VITE_ALLOWED_DOMAINS}
      VITE_EMBEDDED_APP_URL: ${VITE_EMBEDDED_APP_URL}
    networks:
      - internal

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - react
    networks:
      - internal
      - external
  #UPDATE
  ragchat:
    image: rag-chatbot
    networks:
      - internal
      - external
    command: streamlit run src/app.py --server.port=8502 --server.address=0.0.0.0 --server.baseUrlPath=/chat
    ports:
      - "8502:8502"


networks:
  internal:
    internal: true
  external:
    external: false
