
services:

  react:
    build:
      context: .
      dockerfile: ./react/Dockerfile
    networks:
      - internal

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - react
    networks:
      - internal
      - external

  ragchat:
    image: rag-chatbot
    networks:
      - internal
    # run with the following command: streamlit run app.py
    command: streamlit run app.py server.baseUrlPath=/chat

    ports:
      - "8502:8501"


networks:
  internal:
    internal: true
  external:
    external: false
