version: '3.8'

services:
  react-app:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "4173" # Exposed internally but not accessible directly
    expose:
      - "4173" # Allows Nginx to access it within the Docker network
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # Ensure Certbot files are mapped correctly
    depends_on:
      - react-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
